### PR TITLE
Sulaimon itinerary

### PR DESCRIPTION
**Pull request by ekundayoSO**

### CODE REVIEW

**Review by bishnu-suyel — APPROVED** [review]
two .post methods are chained together, both of them are working or only one address ?

**Comment by tauoms** [comment]
Bishnu: The red line means it has been changed, the green line is what it has been changed to. You can see the line number is the same on the left.

**Review by tauoms — APPROVED** [review]
Seems good!

**Comment by bishnu-suyel** [comment]
> Bishnu: The red line means it has been changed, the green line is what it has been changed to. You can see the line number is the same on the left.

Thanks tauoms, I got it now 👍

**Pull request merged**
